//! Host-side facade for the `multisig_v1` RISC Zero guest.
//!
//! Re-exports the compiled guest ELF (`MULTISIG_V1_GUEST_ELF`) and image ID
//! (`MULTISIG_V1_GUEST_ID`) generated by the `multisig-v1-methods` build script. Provides
//! `prove_consumed` / `prove_created` helpers that wrap the witness in the dispatch enum the
//! guest expects, build an `ExecutorEnv`, run the prover, and return a `Receipt`.

use risc0_zkvm::{default_prover, ExecutorEnv, ProverOpts, Receipt, VerifierContext};
use thiserror::Error;

pub use multisig_core::witness::{
    MultisigBranchWitness, MultisigConsumedWitness, MultisigCreatedWitness, SignerSlot,
};
pub use multisig_v1_methods::{MULTISIG_V1_GUEST_ELF, MULTISIG_V1_GUEST_ID};

#[derive(Debug, Error)]
pub enum ProveError {
    #[error("env build: {0}")]
    Env(String),
    #[error("prove: {0}")]
    Prove(String),
}

fn prove_branch(branch: &MultisigBranchWitness, opts: ProverOpts) -> Result<Receipt, ProveError> {
    let env = ExecutorEnv::builder()
        .write(branch)
        .map_err(|e| ProveError::Env(e.to_string()))?
        .build()
        .map_err(|e| ProveError::Env(e.to_string()))?;

    let prove_info = default_prover()
        .prove_with_ctx(env, &VerifierContext::default(), MULTISIG_V1_GUEST_ELF, &opts)
        .map_err(|e| ProveError::Prove(e.to_string()))?;

    Ok(prove_info.receipt)
}

pub fn prove_consumed(witness: MultisigConsumedWitness, opts: ProverOpts) -> Result<Receipt, ProveError> {
    prove_branch(&MultisigBranchWitness::Consumed(witness), opts)
}

pub fn prove_created(witness: MultisigCreatedWitness, opts: ProverOpts) -> Result<Receipt, ProveError> {
    prove_branch(&MultisigBranchWitness::Created(witness), opts)
}
